#!/usr/local/bin/gawk -f
# like this, you can move the contents of a addressfile, if you want
# to include a new field. (not very sophisticated, though)
#
# Attention: Index here begins with 1 whereas in addressbook,
# it begins with 0
#
BEGIN {FS=";";OFS=";"}
{
$18=$17
$17=$16
$16=$15
$15=$14
$14=$13
$13=$12
$12=$11
$11=$10
$10=$9
$9=$8
$8=$7
$7=$5
$5=$6
$6=""
print $0
}
